### ISSUE TITLE
Community Theme

### ISSUE THREAD

**Issue by lixxbox** [Dario-Ciceri/cp2077-mainsail-theme#1]
Hey, 
to get listed at [https://docs.mainsail.xyz/theming/themes](https://docs.mainsail.xyz/theming/themes) I would ask you to put a "screenshot.png" in the root directory. Preferably without browser elements like scrollbars.

After that you can ping me here.

kind regards

**Comment by Dario-Ciceri** [comment]
> Hey,
> to get listed at https://docs.mainsail.xyz/theming/themes I would ask you to put a "screenshot.png" in the root directory. Preferably without browser elements like scrollbars.
> 
> After that you can ping me here.
> 
> kind regards

is it okay?

**Comment by lixxbox** [comment]
I have added your theme! Thanks again!

https://docs.mainsail.xyz/theming/themes
